// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlaaqjomqbiadokmvbor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYWFxam9tcWJpYWRva212Ym9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODMxMDAsImV4cCI6MjA3Mzg1OTEwMH0.hBPcIhzwfIDOnW_Q5_-xCehXi0aw9GJmmg52rqUCE20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'her'
  }
});